@startuml
left to right direction
[*] --> メニュー
メニュー --> 予約と確認 :予約をする
予約と確認 --> あなたの順番 :順番を確認する
あなたの順番 --> 予約と確認 :順番を取消する

予約と確認 --> あなたの順番 :登録ボタンを押す
あなたの順番 --> あなたの順番 :確認ボタンを押す
あなたの順番 --> メニュー :取消ボタンを押す

あなたの順番 --> 今の順番 :診察が終了

今の順番 --> 今の順番 :看護士が次の患者へ
メニュー --> [*]
@enduml