@startuml
left to right direction
actor 利用者 as User
actor 看護師 as Nurse

rectangle システム {
usecase メニュー画面 as a
usecase 予約と確認画面 as b
usecase あなたの順番画面 as c
usecase 今の順番画面 as d
usecase 予約取り消し as e
usecase 今の順番表示 as f
usecase 名前と電話番号を入力 as g
usecase 登録ボタンを押す as h
usecase 自分の順番を確認 as i
usecase 自分の順番を取り消す as j

User -- a
User -- b
User -- c
User -- d
User --> e
Nurse --> f

  a --> b
  b --> c
  b --> d
  b --> e

User --> g
User --> h
User --> i
User --> j

g ..> b : <<include>>
h ..> b : <<include>>
i ..> c : <<include>>
j ..> e : <<include>>
f ..> d : <<include>>
}

@enduml