@startuml
left to right direction
object "<u>A: 客クラス</u>" as a {
チェックイン日：五月三日
}
object "<u>B: 客クラス</u>" as b {
チェックイン日：五月三日
}
object "<u>３０１: 部屋クラス</u>" as c {
タイプ：シングル
宿泊料：１１,０００
キャンペーン価格：９０００

}
object "<u>３０２: 部屋クラス</u>" as d {
    タイプ：シングル
宿泊料：１１,０００
キャンペーン価格：９０００
}
object "<u>３０３: 部屋クラス</u>" as e {
    タイプ：シングル
宿泊料：１１,０００
キャンペーン価格：９０００
}
a--c
b--e