@startuml 例題1
left to right direction
actor 利用者 as a
actor 看護師 as b
rectangle 診察予約システム {
usecase 予約する as c
usecase 自分の順番を確認する as d
usecase 順番を取り消す as e
usecase 今の番号を変更する as f
}
a-->c
a-->d
a-->e
f<--b
@enduml