@startuml
hide footbox
Actor 客 as member
participant ":フロア店員" as boundary
participant ":料理人" as control
mainframe sd ラーメン屋さん
activate member
member -> boundary : ラーメンを注文する
activate boundary
boundary -> control : 料理を指示する
activate control
control -> control : 料理をする
boundary <-- control : ラーメン
member <-- boundary: ラーメン
@enduml